import { loadDb, saveDb, type DbSchema } from './store';

function hashPassword(password: string): string {
  let hash = 0;
  for (let i = 0; i < password.length; i++) { const c = password.charCodeAt(i); hash = ((hash << 5) - hash) + c; hash |= 0; }
  return `local_hash_${Math.abs(hash).toString(36)}_${password.length}`;
}

export function verifyPassword(password: string, hash: string): boolean { return hashPassword(password) === hash; }
export function createPasswordHash(password: string): string { return hashPassword(password); }

const CATEGORIES = [
  { id: 'cat-electronics', name: 'Electronics', slug: 'electronics', description: 'Gadgets, devices, and tech accessories', image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=600&h=400&fit=crop&auto=format' },
  { id: 'cat-clothing', name: 'Clothing', slug: 'clothing', description: 'Apparel, shoes, and fashion accessories', image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=600&h=400&fit=crop&auto=format' },
  { id: 'cat-home', name: 'Home & Kitchen', slug: 'home-kitchen', description: 'Kitchen tools, decor, and home essentials', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=400&fit=crop&auto=format' },
  { id: 'cat-books', name: 'Books', slug: 'books', description: 'Fiction, non-fiction, and technical reading', image: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=600&h=400&fit=crop&auto=format' },
  { id: 'cat-sports', name: 'Sports & Outdoors', slug: 'sports-outdoors', description: 'Fitness equipment and outdoor gear', image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&h=400&fit=crop&auto=format' },
  { id: 'cat-beauty', name: 'Beauty & Personal Care', slug: 'beauty', description: 'Skincare, grooming, and personal care products', image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&h=400&fit=crop&auto=format' },
];

const PRODUCTS = [
  { id: 'prod-001', name: 'Wireless Noise-Cancelling Headphones', slug: 'wireless-nc-headphones', description: 'Premium over-ear headphones with active noise cancellation, 30-hour battery life, and Hi-Res audio support.', price: 7999, compareAtPrice: 9999, category: 'Electronics', images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop&auto=format','https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&h=600&fit=crop&auto=format','https://images.unsplash.com/photo-1487215078519-e21cc028cb29?w=600&h=600&fit=crop&auto=format'], specifications: { 'Battery Life': '30 hours', 'Driver Size': '40mm', 'Connectivity': 'Bluetooth 5.2', 'Noise Cancellation': 'Active (ANC)' }, tags: ['wireless','noise-cancelling','bluetooth'], featured: true, stock: 15, lowStockThreshold: 5 },
  { id: 'prod-002', name: 'USB-C Fast Charger 65W', slug: 'usb-c-fast-charger', description: 'Compact GaN charger with 65W output. Compatible with laptops, tablets, and phones.', price: 3499, compareAtPrice: null, category: 'Electronics', images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&h=600&fit=crop&auto=format'], specifications: { 'Wattage': '65W', 'Technology': 'GaN III' }, tags: ['charger','usb-c'], featured: false, stock: 42, lowStockThreshold: 10 },
  { id: 'prod-003', name: 'Mechanical Gaming Keyboard', slug: 'mechanical-gaming-keyboard', description: 'Compact 75% layout with hot-swappable switches, per-key RGB backlighting, and aluminum frame.', price: 12999, compareAtPrice: 14999, category: 'Electronics', images: ['https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600&h=600&fit=crop&auto=format','https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&h=600&fit=crop&auto=format'], specifications: { 'Layout': '75%', 'Switches': 'Hot-swappable', 'Backlighting': 'Per-key RGB' }, tags: ['keyboard','mechanical','gaming'], featured: true, stock: 8, lowStockThreshold: 3 },
  { id: 'prod-004', name: 'Portable Bluetooth Speaker', slug: 'portable-bluetooth-speaker', description: 'Waterproof (IP67) speaker with 360-degree sound and 12-hour playtime.', price: 4999, compareAtPrice: null, category: 'Electronics', images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&h=600&fit=crop&auto=format'], specifications: { 'Battery': '12 hours', 'Waterproofing': 'IP67' }, tags: ['speaker','bluetooth','waterproof'], featured: false, stock: 0, lowStockThreshold: 5 },
  { id: 'prod-005', name: 'Wireless Ergonomic Mouse', slug: 'wireless-ergonomic-mouse', description: 'Vertical ergonomic mouse with 6 programmable buttons and 90-day battery life.', price: 4299, compareAtPrice: null, category: 'Electronics', images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&h=600&fit=crop&auto=format'], specifications: { 'DPI': 'Up to 4000', 'Buttons': '6 programmable' }, tags: ['mouse','ergonomic'], featured: false, stock: 27, lowStockThreshold: 8 },
  { id: 'prod-006', name: '4K Webcam with Ring Light', slug: '4k-webcam-ring-light', description: 'Ultra-HD webcam with built-in ring light and dual noise-cancelling microphones.', price: 8999, compareAtPrice: 10999, category: 'Electronics', images: ['https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&h=600&fit=crop&auto=format'], specifications: { 'Resolution': '4K @ 30fps' }, tags: ['webcam','4k','streaming'], featured: false, stock: 12, lowStockThreshold: 4 },
  { id: 'prod-007', name: 'Smart LED Strip Lights 5m', slug: 'smart-led-strip-lights', description: 'Wi-Fi controlled 5m LED strip with 16 million colours and music sync.', price: 2299, compareAtPrice: null, category: 'Electronics', images: ['https://images.unsplash.com/photo-1615796153287-98eacf0abb13?w=600&h=600&fit=crop&auto=format'], specifications: { 'Length': '5 metres', 'Connectivity': 'Wi-Fi' }, tags: ['led','smart-home'], featured: false, stock: 55, lowStockThreshold: 15 },
  { id: 'prod-010', name: 'Classic Cotton T-Shirt', slug: 'classic-cotton-tshirt', description: 'Premium ring-spun cotton crew neck. Pre-shrunk, garment-dyed. Unisex relaxed fit.', price: 1999, compareAtPrice: null, category: 'Clothing', images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=600&fit=crop&auto=format','https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&h=600&fit=crop&auto=format'], specifications: { 'Material': '100% ring-spun cotton', 'Fit': 'Relaxed unisex' }, tags: ['t-shirt','cotton','basics'], featured: false, stock: 120, lowStockThreshold: 20 },
  { id: 'prod-011', name: 'Denim Jacket', slug: 'denim-jacket', description: 'Classic vintage-wash denim jacket with antique brass buttons and chest pockets.', price: 6999, compareAtPrice: 8999, category: 'Clothing', images: ['https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=600&h=600&fit=crop&auto=format','https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&h=600&fit=crop&auto=format'], specifications: { 'Material': '12oz cotton denim', 'Closure': 'Button front' }, tags: ['denim','jacket','vintage'], featured: true, stock: 18, lowStockThreshold: 5 },
  { id: 'prod-012', name: 'Running Shoes', slug: 'running-shoes', description: 'Lightweight running shoes with engineered mesh upper and responsive foam midsole.', price: 8999, compareAtPrice: null, category: 'Clothing', images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop&auto=format','https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600&h=600&fit=crop&auto=format','https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&h=600&fit=crop&auto=format'], specifications: { 'Upper': 'Engineered mesh', 'Midsole': 'Responsive foam' }, tags: ['shoes','running','athletic'], featured: true, stock: 25, lowStockThreshold: 8 },
  { id: 'prod-013', name: 'Merino Wool Hoodie', slug: 'merino-wool-hoodie', description: 'Premium merino wool blend hoodie. Naturally temperature-regulating and odour-resistant.', price: 8499, compareAtPrice: null, category: 'Clothing', images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&h=600&fit=crop&auto=format'], specifications: { 'Material': '80% merino wool, 20% nylon' }, tags: ['hoodie','merino','wool'], featured: false, stock: 22, lowStockThreshold: 6 },
  { id: 'prod-014', name: 'Slim-Fit Chinos', slug: 'slim-fit-chinos', description: 'Modern slim-fit chinos in stretch-cotton twill. Available in navy, stone, and olive.', price: 4999, compareAtPrice: null, category: 'Clothing', images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&h=600&fit=crop&auto=format'], specifications: { 'Material': '98% cotton, 2% elastane', 'Fit': 'Slim' }, tags: ['chinos','pants','slim-fit'], featured: false, stock: 40, lowStockThreshold: 10 },
  { id: 'prod-015', name: 'Waterproof Hiking Boots', slug: 'waterproof-hiking-boots', description: 'Rugged waterproof hiking boots with Vibram outsole and ankle support.', price: 13999, compareAtPrice: 16999, category: 'Clothing', images: ['https://images.unsplash.com/photo-1520219306100-ec4afeeefe58?w=600&h=600&fit=crop&auto=format','https://images.unsplash.com/photo-1606890658317-7d14490b76fd?w=600&h=600&fit=crop&auto=format'], specifications: { 'Upper': 'Full-grain leather + nylon', 'Outsole': 'Vibram' }, tags: ['boots','hiking','waterproof'], featured: false, stock: 9, lowStockThreshold: 3 },
  { id: 'prod-020', name: 'Stainless Steel Water Bottle', slug: 'stainless-steel-water-bottle', description: 'Double-wall vacuum insulated. Keeps drinks cold 24 hours or hot 12 hours.', price: 2499, compareAtPrice: null, category: 'Home & Kitchen', images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=600&fit=crop&auto=format'], specifications: { 'Capacity': '750ml', 'Material': '18/8 stainless steel' }, tags: ['water-bottle','insulated'], featured: false, stock: 60, lowStockThreshold: 15 },
  { id: 'prod-021', name: 'Non-Stick Frying Pan', slug: 'non-stick-frying-pan', description: 'Professional 10-inch frying pan with ceramic non-stick coating. Oven-safe to 230°C.', price: 3299, compareAtPrice: null, category: 'Home & Kitchen', images: ['https://images.unsplash.com/photo-1592154395799-40a15d802539?w=600&h=600&fit=crop&auto=format'], specifications: { 'Size': '10 inches', 'Coating': 'Ceramic non-stick' }, tags: ['pan','non-stick','cooking'], featured: false, stock: 33, lowStockThreshold: 10 },
  { id: 'prod-022', name: 'LED Desk Lamp', slug: 'led-desk-lamp', description: 'Adjustable LED desk lamp with 5 colour temperatures and USB charging port.', price: 4499, compareAtPrice: null, category: 'Home & Kitchen', images: ['https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=600&h=600&fit=crop&auto=format'], specifications: { 'Colour Temps': '5 modes', 'USB Port': 'Yes' }, tags: ['lamp','led','desk'], featured: false, stock: 0, lowStockThreshold: 5 },
  { id: 'prod-023', name: 'Bamboo Cutting Board Set', slug: 'bamboo-cutting-board-set', description: 'Set of 3 premium organic bamboo cutting boards with juice grooves.', price: 2999, compareAtPrice: 3999, category: 'Home & Kitchen', images: ['https://images.unsplash.com/photo-1594226801341-41427b4e5c22?w=600&h=600&fit=crop&auto=format'], specifications: { 'Material': 'Organic bamboo', 'Sizes': '3 (S/M/L)' }, tags: ['cutting-board','bamboo','kitchen'], featured: false, stock: 45, lowStockThreshold: 12 },
  { id: 'prod-024', name: 'French Press Coffee Maker', slug: 'french-press-coffee-maker', description: '34oz borosilicate glass French press with stainless steel plunger and double-wall insulation.', price: 3499, compareAtPrice: null, category: 'Home & Kitchen', images: ['https://images.unsplash.com/photo-1572119865084-43c285814d63?w=600&h=600&fit=crop&auto=format','https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=600&fit=crop&auto=format'], specifications: { 'Capacity': '34oz / 1L', 'Material': 'Borosilicate glass' }, tags: ['coffee','french-press'], featured: true, stock: 20, lowStockThreshold: 6 },
  { id: 'prod-025', name: 'Professional Knife Set', slug: 'professional-knife-set', description: '6-piece Japanese-style chef knife set in walnut block. High-carbon stainless steel.', price: 7999, compareAtPrice: null, category: 'Home & Kitchen', images: ['https://images.unsplash.com/photo-1593618998160-e34014e67546?w=600&h=600&fit=crop&auto=format'], specifications: { 'Pieces': '6 + block', 'Steel': 'High-carbon stainless' }, tags: ['knives','kitchen','professional'], featured: false, stock: 11, lowStockThreshold: 3 },
  { id: 'prod-030', name: 'The Pragmatic Programmer', slug: 'pragmatic-programmer', description: 'Classic guide to software development. Covers best practices and timeless principles.', price: 4295, compareAtPrice: null, category: 'Books', images: ['https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&h=600&fit=crop&auto=format'], specifications: { 'Author': 'David Thomas, Andrew Hunt', 'Pages': '352' }, tags: ['programming','software','classic'], featured: false, stock: 50, lowStockThreshold: 10 },
  { id: 'prod-031', name: 'Design Patterns in TypeScript', slug: 'design-patterns-typescript', description: 'Comprehensive guide to Gang of Four design patterns in modern TypeScript.', price: 3799, compareAtPrice: null, category: 'Books', images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&h=600&fit=crop&auto=format'], specifications: { 'Pages': '420', 'Level': 'Intermediate–Advanced' }, tags: ['typescript','design-patterns'], featured: false, stock: 14, lowStockThreshold: 5 },
  { id: 'prod-032', name: 'Cooking for Engineers', slug: 'cooking-for-engineers', description: 'A systematic approach to cooking with precise measurements and scientific explanations.', price: 2899, compareAtPrice: null, category: 'Books', images: ['https://images.unsplash.com/photo-1589998059171-988d887df646?w=600&h=600&fit=crop&auto=format'], specifications: { 'Pages': '288', 'Level': 'Beginner–Intermediate' }, tags: ['cooking','food','science'], featured: false, stock: 7, lowStockThreshold: 3 },
  { id: 'prod-033', name: 'Clean Architecture', slug: 'clean-architecture', description: 'Robert C. Martin\'s guide to software structure and design principles.', price: 4499, compareAtPrice: null, category: 'Books', images: ['https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&h=600&fit=crop&auto=format'], specifications: { 'Author': 'Robert C. Martin', 'Pages': '432' }, tags: ['architecture','software','design'], featured: false, stock: 30, lowStockThreshold: 8 },
  { id: 'prod-040', name: 'Adjustable Dumbbell Set', slug: 'adjustable-dumbbell-set', description: 'Space-saving adjustable dumbbells. Weight range: 5–52.5 lbs per dumbbell.', price: 29999, compareAtPrice: 34999, category: 'Sports & Outdoors', images: ['https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?w=600&h=600&fit=crop&auto=format','https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&h=600&fit=crop&auto=format'], specifications: { 'Weight Range': '5–52.5 lbs', 'Replaces': '15 pairs' }, tags: ['dumbbells','weights','fitness'], featured: true, stock: 6, lowStockThreshold: 2 },
  { id: 'prod-041', name: 'Yoga Mat with Alignment Lines', slug: 'yoga-mat-alignment', description: '6mm thick eco-friendly TPE yoga mat with alignment lines. Includes carry strap.', price: 3999, compareAtPrice: null, category: 'Sports & Outdoors', images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&h=600&fit=crop&auto=format'], specifications: { 'Thickness': '6mm', 'Material': 'TPE (eco-friendly)' }, tags: ['yoga','mat','eco-friendly'], featured: false, stock: 38, lowStockThreshold: 10 },
  { id: 'prod-042', name: 'Insulated Hiking Backpack 35L', slug: 'insulated-hiking-backpack', description: 'Waterproof 35L daypack with hydration sleeve and padded hip belt.', price: 8999, compareAtPrice: null, category: 'Sports & Outdoors', images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop&auto=format'], specifications: { 'Capacity': '35L', 'Waterproof': 'Yes + rain cover' }, tags: ['backpack','hiking','waterproof'], featured: false, stock: 14, lowStockThreshold: 4 },
  { id: 'prod-043', name: 'GPS Running Watch', slug: 'gps-running-watch', description: 'Multi-sport GPS watch with heart rate, blood oxygen monitoring, and 7-day battery.', price: 19999, compareAtPrice: 24999, category: 'Sports & Outdoors', images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop&auto=format','https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&h=600&fit=crop&auto=format'], specifications: { 'GPS': 'Multi-band', 'Battery': '7 days' }, tags: ['watch','gps','running'], featured: true, stock: 0, lowStockThreshold: 3 },
  { id: 'prod-050', name: 'Vitamin C Brightening Serum', slug: 'vitamin-c-serum', description: '20% L-ascorbic acid serum with hyaluronic acid and vitamin E. Dermatologist tested.', price: 2999, compareAtPrice: null, category: 'Beauty & Personal Care', images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&h=600&fit=crop&auto=format'], specifications: { 'Active': '20% L-ascorbic acid', 'Size': '30ml' }, tags: ['serum','vitamin-c','skincare'], featured: false, stock: 65, lowStockThreshold: 15 },
  { id: 'prod-051', name: 'Natural Bamboo Toothbrush Set', slug: 'bamboo-toothbrush-set', description: 'Pack of 4 biodegradable bamboo toothbrushes with BPA-free bristles.', price: 1199, compareAtPrice: null, category: 'Beauty & Personal Care', images: ['https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=600&h=600&fit=crop&auto=format'], specifications: { 'Quantity': '4 pack', 'Material': 'Moso bamboo' }, tags: ['toothbrush','bamboo','eco'], featured: false, stock: 90, lowStockThreshold: 20 },
  { id: 'prod-052', name: 'Professional Hair Dryer', slug: 'professional-hair-dryer', description: '2200W ionic hair dryer with ceramic tourmaline technology. Includes concentrator and diffuser.', price: 5999, compareAtPrice: 7499, category: 'Beauty & Personal Care', images: ['https://images.unsplash.com/photo-1522338140262-f46f5913618a?w=600&h=600&fit=crop&auto=format'], specifications: { 'Wattage': '2200W', 'Technology': 'Ionic + ceramic' }, tags: ['hair-dryer','professional'], featured: false, stock: 17, lowStockThreshold: 5 },
  { id: 'prod-053', name: 'SPF 50 Sunscreen Lotion', slug: 'spf50-sunscreen', description: 'Broad-spectrum UVA/UVB sunscreen. Lightweight, non-greasy. Water resistant 80 minutes.', price: 1599, compareAtPrice: null, category: 'Beauty & Personal Care', images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&h=600&fit=crop&auto=format'], specifications: { 'SPF': '50', 'Water Resistant': '80 minutes' }, tags: ['sunscreen','spf','skincare'], featured: false, stock: 80, lowStockThreshold: 20 },
];

const USERS = [
  { id: 'user-admin', email: 'admin@shopwave.com', name: 'Admin User', password: 'admin123', role: 'ADMIN' as const },
  { id: 'user-demo', email: 'demo@shopwave.com', name: 'Demo Customer', password: 'demo123', role: 'USER' as const },
  { id: 'user-jane', email: 'jane@example.com', name: 'Jane Smith', password: 'jane123', role: 'USER' as const },
];

const PROMOTIONS = [
  { id: 'promo-001', code: 'SAVE10', type: 'percentage' as const, value: 10, minOrderAmount: 2000, maxDiscount: 5000, usageLimit: null, usageCount: 0, description: '10% off (up to $50 off, min $20)', active: true, startsAt: '2024-01-01T00:00:00Z', expiresAt: '2027-12-31T23:59:59Z' },
  { id: 'promo-002', code: 'WELCOME5', type: 'fixed' as const, value: 500, minOrderAmount: 1500, maxDiscount: null, usageLimit: 1000, usageCount: 42, description: '$5 off (min $15)', active: true, startsAt: '2024-01-01T00:00:00Z', expiresAt: '2027-12-31T23:59:59Z' },
  { id: 'promo-003', code: 'FREESHIP', type: 'free_shipping' as const, value: 0, minOrderAmount: 1000, maxDiscount: null, usageLimit: null, usageCount: 0, description: 'Free shipping on orders over $10', active: true, startsAt: '2024-01-01T00:00:00Z', expiresAt: '2027-12-31T23:59:59Z' },
  { id: 'promo-004', code: 'EXPIRED20', type: 'percentage' as const, value: 20, minOrderAmount: 5000, maxDiscount: 10000, usageLimit: 100, usageCount: 100, description: '20% off (expired)', active: false, startsAt: '2023-01-01T00:00:00Z', expiresAt: '2023-12-31T23:59:59Z' },
  { id: 'promo-005', code: 'SUMMER25', type: 'percentage' as const, value: 25, minOrderAmount: 5000, maxDiscount: 7500, usageLimit: 500, usageCount: 0, description: '25% off summer sale (up to $75, min $50)', active: true, startsAt: '2024-06-01T00:00:00Z', expiresAt: '2027-09-30T23:59:59Z' },
];

const REVIEWS = [
  { id: 'rev-001', productId: 'prod-001', userId: 'user-demo', authorName: 'Demo Customer', rating: 5, title: 'Best headphones I\'ve owned', body: 'The noise cancellation is incredible. Battery lasts forever. Sound quality rivals headphones costing twice as much.', verified: true, status: 'approved' as const, helpfulVotes: 12 },
  { id: 'rev-002', productId: 'prod-001', userId: 'user-jane', authorName: 'Jane Smith', rating: 4, title: 'Great sound, minor comfort issue', body: 'Sound quality is top-notch and the ANC works beautifully. Only 4 stars because after 3+ hours they press a bit on my ears.', verified: true, status: 'approved' as const, helpfulVotes: 8 },
  { id: 'rev-003', productId: 'prod-003', userId: 'user-demo', authorName: 'Demo Customer', rating: 5, title: 'Endgame keyboard', body: 'Hot-swap switches are a game changer. The aluminum frame feels incredibly solid and the sound profile is perfect.', verified: true, status: 'approved' as const, helpfulVotes: 15 },
  { id: 'rev-004', productId: 'prod-012', userId: 'user-jane', authorName: 'Jane Smith', rating: 4, title: 'Comfortable for daily runs', body: 'Been using these for daily 5K runs for two months. Very comfortable, good support, and the mesh keeps feet cool.', verified: true, status: 'approved' as const, helpfulVotes: 6 },
  { id: 'rev-005', productId: 'prod-024', userId: 'user-demo', authorName: 'Demo Customer', rating: 5, title: 'Perfect morning coffee', body: 'Makes the richest, most full-bodied coffee. The double-wall insulation keeps it warm. Easy to clean and looks elegant.', verified: true, status: 'approved' as const, helpfulVotes: 9 },
];

export function seedDatabase(): void {
  const db = loadDb();
  if (db.users.length > 0) return;
  const now = new Date().toISOString();
  db.users = USERS.map(u => ({ id: u.id, email: u.email, name: u.name, passwordHash: createPasswordHash(u.password), role: u.role, createdAt: now }));
  db.categories = CATEGORIES;
  db.products = PRODUCTS.map(p => ({ ...p, specifications: p.specifications as unknown as Record<string, string>, status: 'active' as const, createdAt: now, updatedAt: now }));
  db.inventoryLogs = PRODUCTS.map(p => ({ id: `invlog-${p.id}`, productId: p.id, previousStock: 0, newStock: p.stock, change: p.stock, reason: 'initial' as const, referenceId: null, createdAt: now }));
  db.promotions = PROMOTIONS.map(p => ({ ...p, createdAt: now }));
  db.reviews = REVIEWS.map(r => ({ ...r, createdAt: now, updatedAt: now }));
  saveDb(db);
}
