'use client';
import { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { motion, AnimatePresence } from 'framer-motion';
import Button from '../ui/Button';
interface CartItem { productId: string; productName: string; productImage: string; productSlug: string; price: number; quantity: number; subtotal: number; stock: number; }
function fp(c: number) { return `$${(c/100).toFixed(2)}`; }
export default function CartDrawer({ isOpen, onClose }: { isOpen: boolean; onClose: () => void }) {
  const [items, setItems] = useState<CartItem[]>([]); const [subtotal, setSubtotal] = useState(0); const [loading, setLoading] = useState(false); const [upd, setUpd] = useState<string|null>(null);
  const fetch_ = useCallback(async () => { setLoading(true); try { const r = await fetch('/api/cart'); const j = await r.json(); if (j.success) { setItems(j.data.items); setSubtotal(j.data.subtotal); } } finally { setLoading(false); } }, []);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (isOpen) fetch_(); }, [isOpen, fetch_]);
  useEffect(() => { if (!isOpen) return; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = ''; }; }, [isOpen]);
  async function uq(pid: string, q: number) { setUpd(pid); try { if (q===0) await fetch('/api/cart/items',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:pid})}); else await fetch('/api/cart/items',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:pid,quantity:q})}); await fetch_(); } finally { setUpd(null); } }
  return <AnimatePresence>{isOpen && <div className="fixed inset-0 z-[55]"><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="absolute inset-0 bg-black/50" onClick={onClose}/><motion.aside initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{type:'spring',damping:30,stiffness:300}} className="absolute right-0 top-0 bottom-0 w-full max-w-md bg-white shadow-xl flex flex-col">
    <div className="flex items-center justify-between border-b px-4 py-4"><h2 className="text-lg font-semibold">Cart</h2><button onClick={onClose} aria-label="Close" className="text-gray-400 hover:text-gray-600"><svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12"/></svg></button></div>
    <div className="flex-1 overflow-y-auto px-4 py-4">{loading?<div className="space-y-4">{[1,2].map(n=><div key={n} className="flex gap-3 animate-pulse"><div className="h-16 w-16 rounded bg-gray-200"/><div className="flex-1 space-y-2"><div className="h-4 w-3/4 bg-gray-200 rounded"/><div className="h-3 w-1/2 bg-gray-200 rounded"/></div></div>)}</div>:items.length===0?<div className="text-center py-12"><p className="text-sm text-gray-500">Cart is empty</p><Button size="sm" className="mt-4" onClick={onClose}>Shop</Button></div>:<div className="space-y-4">{items.map(i=><div key={i.productId} className="flex gap-3"><div className="relative h-16 w-16 flex-shrink-0 rounded bg-gray-100 overflow-hidden">{i.productImage?<Image src={i.productImage} alt={i.productName} fill sizes="64px" className="object-cover"/>:<div className="flex h-full w-full items-center justify-center text-gray-300 text-xs">N/A</div>}</div><div className="flex-1 min-w-0"><Link href={`/products/${i.productSlug}`} onClick={onClose} className="text-sm font-medium text-gray-900 hover:text-blue-600 line-clamp-1">{i.productName}</Link><p className="text-sm text-gray-500">{fp(i.price)}</p><div className="mt-1 flex items-center gap-2"><button onClick={()=>uq(i.productId,i.quantity-1)} disabled={upd===i.productId} className="flex h-6 w-6 items-center justify-center rounded border text-xs hover:bg-gray-50 disabled:opacity-50">−</button><span className="text-sm w-6 text-center">{i.quantity}</span><button onClick={()=>uq(i.productId,i.quantity+1)} disabled={upd===i.productId||i.quantity>=i.stock} className="flex h-6 w-6 items-center justify-center rounded border text-xs hover:bg-gray-50 disabled:opacity-50">+</button><span className="ml-auto text-sm font-medium">{fp(i.subtotal)}</span></div></div></div>)}</div>}</div>
    {items.length>0&&<div className="border-t px-4 py-4 space-y-3"><div className="flex justify-between text-sm"><span className="text-gray-600">Subtotal</span><span className="font-semibold">{fp(subtotal)}</span></div><Link href="/checkout" onClick={onClose} className="block w-full rounded-md bg-blue-600 py-2.5 text-center text-sm font-semibold text-white hover:bg-blue-700">Checkout</Link><Link href="/cart" onClick={onClose} className="block text-center text-sm text-blue-600 hover:underline">View Cart</Link></div>}
  </motion.aside></div>}</AnimatePresence>;
}
